slac-lcls/smalldata_tools

- smalldata_tools/utilities.py
adding a function to get optimal cuts programmatically
> add function to get optimal cuts for input variables

- smalldata_tools/SmallDataDefaultDetector.py
change code for other bldDetectors to grab all fields present rather than hardcoding them
code change in preparation for new diamcc translation.
> add detector for eorbits

- examples/GhostFitData.py
- examples/GhostFitFit.py
- examples/LoadSmallDataAna.py
- examples/MakeCube.py
- examples/MakeCube_test.py
- examples/MakeLocalPedestal.py
- examples/PickedEventsCube.py
- examples/SaveAvImage.py
- examples/SmallDataProducer.py
- examples/SmallDataProducer_userData.py
- examples/SumCubes.py
- examples/runSmallDataAna
- examples/smallDataRun
- smalldata_tools/CubeAna.py
- smalldata_tools/DetObject.py
- smalldata_tools/GaussFit.py
- smalldata_tools/SmallDataAna.py
- smalldata_tools/SmallDataAna_psana.py
- smalldata_tools/SmallDataDefaultDetector.py
- smalldata_tools/SmallDataUtils.py
- smalldata_tools/azimuthalBinning.py
- smalldata_tools/epicsarchive.py
- smalldata_tools/fitCenter.py
- smalldata_tools/read_uxi.py
- smalldata_tools/roi_rebin.py
- smalldata_tools/utilities.py
- smalldata_tools/utilities_plotting.py
- smalldata_tools/waveformFunc.py
Tested simple data production. Could not test analysis code as packages were missing.
The changes are pretty simple, but touch most files due to the different print style formatting and a few other things. As the py3 release I had did not have krtc or holoviews, I could not test everything, but ran both production and analysis in python2-psana, so at least we should not go backwards.
> changes to make more (more) compatible with python3.

- arp_scripts/submit_small_data.sh
- examples/smalldata_producer_full_arp.py
- smalldata_tools/SmallDataDefaultDetector.py
- smalldata_tools/SmallDataUtils.py
fixed issue with epicsDetector when run in mode where missing PVs would be accepted.
Fixed a few small other oversights that could cause problems for automatic full translation
Initial version of auto-full translation (needs more tests when ior-recording works again)
> Work in preparation for commissioning.

- arp_scripts/submit_small_data.sh
- examples/smalldata_producer_arp.py
- examples/smalldata_producer_full_arp.py
also remove time limit on slurm
updating counter on ARP page
> Towards full translation (XTCAV,...)

- arp_scripts/submit_jt_cal.sh
- examples/jt_cal.py
Initial jt calibration script to run through ARP
ARP/SLURM output:
2020-06-05 17:28:32,784 - DEBUG - slurm_script:calc_intensity_bounds - Getting intensity data for {i_mon}
2020-06-05 17:28:32,860 - DEBUG - slurm_script:calc_intensity_bounds - Lower:Upper bounds for intensity monitor: 1.97:3.06
2020-06-05 17:28:32,863 - DEBUG - slurm_script:det_azav - Getting azimuthal values for detector: DsaCsPad
2020-06-05 17:28:34,132 - DEBUG - slurm_script:det_azav - Found average azimuthal average array from all events
2020-06-05 17:28:34,133 - DEBUG - slurm_script:calc_peak_and_intensity - Fitting Guassian of average azimuthal binned array
2020-06-05 17:28:34,144 - DEBUG - slurm_script:calc_peak_and_intensity - Peak found at 147, with and intensity of 237.04
2020-06-05 17:28:34,146 - DEBUG - …
> initial jt cal script

- smalldata_tools/SmallDataAna.py
- smalldata_tools/utilities_plotting.py
What the title said. several small fixes necessary due to module updates.
> fixed a few small issues with the analysis tools

- smalldata_tools/DetObject.py
Add code to make a summed image for a detector.
> add detector sum

- examples/smalldata_producer_arp.py
- smalldata_tools/SmallDataUtils.py
ARP to print -1 if a run has no events
Add MEC PVs from epics_arch code
> add PV to MEC list, ARP prints when no events are found

- arp_scripts/submit_small_data.sh
- arp_scripts/submit_small_data_inner.sh
- arp_scripts/submit_small_data_outer.sh
- examples/smalldata_producer_full_arp.py
Put image & tiff file option back in the code. I poorly manage code when supporting experiments that need small fixes and run on a variety of generations of code.
> put image&tiff file processing back in

- arp_scripts/submit_plots.sh
- examples/DataqualityPlots.py
changes to data quality plots
make ready for ARP submission
post variables to run summary table
> data quality plots

- arp_scripts/submit_smd.sh
- examples/BeamlineSummaryPlots.py
- examples/DataqualityPlots.py
- examples/runSmallDataAna
- examples/smalldata_producer.py
- smalldata_tools/SmallDataAna.py
- smalldata_tools/SmallDataAna_psana.py
Few bug fixed for smallDataAna, updates to summary plots
> Mostly smaller changes and fixes for xpplw0018

- examples/MakeCube.py
- examples/smalldata_producer.py
Otherwise the roundtables will become unhappy and that might affect the DAQ which is not good.
> only post from rank 0 to runtables

- .gitignore
- arp_scripts/submit_small_data.sh
- examples/check_local.sh
- examples/smalldata_producer.py
/example/smalldata_producer.py : Custom exception hook to abort MPI when a single rank fails.
/example/smalldata_producer.py : Improved version of define_dets function.
/example/check_locals.sh : Small bash script to quickly check things locally.
/arp_scripts/submit_smalldata.sh : add 002 mask for file and directories creation
> Xpplv0918 improvement

- smalldata_tools/ana_funcs/azimuthalBinning.py
also add square option to calculate theh std within a bin using  both the mean and the mean of the squares
> add z-coordinates from geometry to the azimuthal averaging code

- smalldata_tools/ana_funcs/photons.py
invert mask when passing to masked array as the intepretation of how a mask is used different from the masked array to the psana photon function
> Invert mask to make masked array

- arp_scripts/submit_small_data.sh
- examples/smd2_producer.py
- smalldata_tools/utilities_waveforms.py
adding some functions for waveform processing from Andrei Kamalov for TMO. Also fix some problems in the producer files for running with MPI
> added utilities_waveforms&fix a few things inthe producer

- smalldata_tools/ana_funcs/azimuthalBinning.py
- smalldata_tools/ana_funcs/droplet.py
- smalldata_tools/ana_funcs/droplet2Func.py
I added a new DetObjectFunc to do droplet analysis. The arguments you could put into this function include return_img (bool), name, threshold, mask, aduspphot, and offset. This class has a function called process that processes the function for each image. It uses the functions convert_img, loopdrops, and getProb_img to return a dictionary including the probability and either the photon list (as ragged so it is split into two arrays x's and y's) or the image with how many photons there is at each coordinate in the image.
> Droplet2 func

- setup_scripts/smd_go_offline.sh
- setup_scripts/update_arp_jobs.py
Quick fix of a couple things I noticed when running the setup scripts for the first time earlier this month.
> BUG: Fix a couple small typos

- smalldata_tools/SmallDataAna_psana.py
Several option for MakeMask for the epix10k[2M] were broken. Fixed that.
> fix MakeMask issues for epix10k2M

- producers/cube_config_xpp.py
- producers/letsCube.py
- setup_scripts/README
- setup_scripts/smd_go_offline.sh
- smalldata_tools/SmallDataAna_psana.py
- smalldata_tools/cube/cube_mpi_fun.py
- smalldata_tools/cube/cube_rank0_utils.py
Add bin histogram to the summary plots.
Add area detector config (ped, rms, etc) to the cubed data
More info on the goodness of cube in the summary plot
Test on lw8419 run 57 and 111. Plots produced as expected, cubed data content as expected.
Not yet. To come in confluence
> More summary plots, det config

- producers/smd_producer.py
Make DetObjectFunc args instantiation fail not silently.
> Det obj arg

- summaries/PedestalPlot.py
Rather small changes to allow plotting of pedestals for the uxi. Will need a tag later to that it can be linked when makepeds is also ready.
> add uxi to detectors we plot pedestals for

- setup_scripts/smd_go_offline.sh
- setup_scripts/update_arp_jobs.py
Make the smd_go_offline script work after Wilko has moved the data and locked the ffb directory
> smd_go_offline improvement

- smalldata_tools/SmallDataAna.py
- smalldata_tools/cube/cube_rank0_utils.py
add lasDelay2 to the getDelay logic in SmallDataAna
> Las delay2

- smalldata_tools/DetObject.py
- smalldata_tools/DetObject_lcls2.py
- smalldata_tools/ana_funcs/azimuthalBinning.py
- smalldata_tools/ana_funcs/droplet.py
- smalldata_tools/ana_funcs/roi_rebin.py
- smalldata_tools/utilities_plotting.py
Enable droplets to work on tiled detectors. Also some work on the imageFunc so that you could make an image from droplets & the sparsify instead of having to do it the other way around.
> Droplets for tiled detectors.

- setup_scripts/make_arp_jobs.py
- smalldata_tools/SmallDataAna_psana.py
- smalldata_tools/epicsarchive.py
Add a summary plot job to the setup scripts
> Summary plots

- producers/letsCube.py
- smalldata_tools/BaseSmallDataAna_psana.py
- smalldata_tools/SmallDataAna.py
- smalldata_tools/SmallDataAna_psana.py
- smalldata_tools/SmallDataAna_psana_lcls2.py
- smalldata_tools/ana_funcs/azav_pyfai.py
- smalldata_tools/epicsarchive.py
Overhaul of the SmallDataAna to prepare for the implementation of the lcls2 SmallDataAna_psana and the lcls2 cube.
Main idea:
Split SmallDataAna_psana into a base class, which is then sub-classed in SmallDataAna_psana and SmallDataAna_psana_lcls2. The base class handles all the functions to work on data that have been loaded (fitting average image, making plots, etc), i.e. eveything that does not deal with the psana layer. The lcls and lcls2 classes implement the functions to load data (such as average image, etc).
This pull request makes this splits, and prepare for the full integration of the lcls2 files, which will be the focus of the next pull request on that branch. 
The lcls2 timestamps are also implemented in SmallDataAna, so that lcls2 data can be properly loaded in the xArray. …
> Small data ana lcls ii: setup

- producers/cube_config_template.py
- producers/letsCube.py
We want to be able to use user-defined bins for lxt and lxt_ttc scans (CXI and MFX in mind here)
> add custom bin for lxt scans

- smalldata_tools/DetObject.py
> add Orca object for images from the fee spectrometer

- smalldata_tools/ana_funcs/roi_rebin.py
- Remove the squeeze from the coord in ROIFunc. To be tested with more detectors and configuration (UED?) to make sure this does not break anything
- Give default image coordinates: In most cases we'll want that anyway. Do we need the coord /  shape definition to be this complex?
> various ana_funcs improvements

- smalldata_tools/DetObject.py
Adding proper treatment of QADC, slight changes for treatment of Acqirirs. Tested with CXi data for Acqirirs & MEC for QADC.
> add treatment of QADC

- producers/smalldata_producer_template.py
- producers/smd_producer.py
- smalldata_tools/ana_funcs/droplet.py
- smalldata_tools/ana_funcs/droplet2Photons.py
- smalldata_tools/ana_funcs/roi_rebin.py
Rename droplet2Func, debug the sparsity for ragged arrays and add sparsify to the producer when running droplet and droplet2Photon.
> MNT: ana functions rename, producer enhancement

- smalldata_tools/BaseSmallDataAna_psana.py
> itertools no longer as izip (or zip) function

- producers/smalldata_producer_template.py
- producers/smd_producer.py
- smalldata_tools/ana_funcs/droplet.py
- smalldata_tools/ana_funcs/droplet2Photons.py
Add entry to the producer template for the droplet2Photons workflow.
> add droplet2phot to producer template

- smalldata_tools/SmallDataDefaultDetector.py
add timetoolV1 and fix logic so that no empty lists will be returned for tt projection data
> Small fixes for timetool processing (fix xpptut15, run 320)

- arp_scripts/submit_small_data.sh
- arp_scripts/submit_smd.sh
- producers/smd_producer.py
- setup_scripts/smd_setup.sh
- smalldata_tools/SmallDataDefaultDetector.py
- smalldata_tools/SmallDataUtils.py
- smalldata_tools/ana_funcs/azav_pyfai.py
- update timetool default det: now automatically find the right baseName (given that the suffix are the same). Might need to be tested for the case where we have mulitple time tools.
- thres arg for pyfai
- syntax
- core argument added explicitly added for interactive mode, inot having was failing the interactive with MPI
> Fix / improve various small things

- smalldata_tools/BaseSmallDataAna_psana.py
- smalldata_tools/DetObject.py
- smalldata_tools/SmallDataAna_psana.py
In order to clarify what's going on, use symbolic names for the detector types.  These have been added to DetObjectClass, which is now imported everywhere.
In addition, there were a couple of consecutive tests for dettype 2 (CsPad), when clearly one of them should have been for 1 (CsPad2M).  
The imgShape was also sometimes set to a full image, not the *shape* of this image.
Also fixed a minor typo in the spelling of "coordinate".
This shouldn't really change anything, but it's an extensive set of changes, so I'd like another set of eyes on them to make sure I haven't broken anything before I start making *real* changes.
> Changed integer constants to DetObjectClass.NAME, etc.

- producers/smd2_producer.py
- producers/smd_producer.py
- smalldata_tools/SmallDataAna_psana.py
- smalldata_tools/SmallDataDefaultDetector.py
- smalldata_tools/SmallDataUtils.py
Also fixed a few typos using "is" to compare to a non-None literal and lcls2_epicsDetector.params_as_dict to actually return the result.
> Added epicsOncePV to smd*_producer.py.

- producers/BldEpics.py
Test the hostname to decide where to look for data files
> ENH: bld epid: autodetect right data directory

- arp_scripts/submit_smd.sh
- producers/smd_producer_pre_sdf.py
- setup_scripts/make_arp_jobs.py
Lower default cores to 125 on s3df after 3 cores are being locked for Weka
> S3df setup

- pyproject.toml
- smalldata_tools/ana_funcs/roi_rebin.py
- tests/conftest.py
- tests/test_Epix630.py
- tests/test_Epix631.py
- tests/test_Rayonix660.py
- tests/test_jungfrau.py
- tests/test_opal.py
- tests/test_zyla.py
Enhanced JungFrau detector tests by adding tests for ROI, Projection, and ROI_Projection functions. Additionally, improved the code in the process function of ProjectionFunc class in roi_rebin.py by removing irrelevant code and fixing the check for masked array variables meanRes/sunRes.
The purpose of these tests is to verify the functionality of the ROI, Projection, and ROI_Projection functions by examining their outputs (number, data type, and shape) for different inputs using fixture. 
This is tested with various input combinations.
some inline comments
> ROI and Projection test

- producers/BldEpics.py
> BldEpics is now s3df ready!

- summaries/PedestalPlot.py
> fix typo introoduced in last commit

- summaries/BeamlineSummaryPlots_mfx.py
Change Log
- Fix indententation error from `BeamlineSummaryPlots_mfx.py`
> BUG: Indent error in MFX BeamlineSummary

- smalldata_tools/ana_funcs/correlations/correlation.py
- smalldata_tools/ana_funcs/correlations/smd_autocorr.py
- smalldata_tools/ana_funcs/roi_rebin.py
- smalldata_tools/ana_funcs/sparsifyFunc.py
Autocorrelation was used for a couple beamtimes at XCS.
Besides fixing some bugs, the illumination correction has been implemented as well.
> Fix and improve autocorr + few other bug fixes

- producers/smd_producer.py
Change Log
-----------------
- Remove `_ffb` tag when posting eLog parameters.
> MNT Remove FFB tag

- arp_scripts/submit_smd.sh
> create default dir for smd-logfiles on S3DF

- arp_scripts/cubeRun.sh
- lcls1_producers/letsCube.py
- smalldata_tools/common/SmallDataAna.py
- smalldata_tools/lcls1/BaseSmallDataAna_psana.py
- smalldata_tools/lcls1/SmallDataAna_psana.py
- smalldata_tools/lcls1/cube/cube_mpi_fun.py
- smalldata_tools/lcls2/DetObject.py
Make cube work with new re-org.
More work will be needed for smalldataAna , as it is more entrenched with LCLS-I than I initially thought. But the cube now works and this should be a good version to test in operation
> cube working

- lcls2_producers/prod_config_rix.py
- lcls2_producers/smd_producer.py
- smalldata_tools/common/epicsarchive.py
Can pass a list of PV in the smalldata config to get data from archiver.
> working archiver pv setup for lcls2

- summaries/BeamlineSummaryPlots_cxi.py
- summaries/BeamlineSummaryPlots_mfx.py
- summaries/BeamlineSummaryPlots_rix.py
- summaries/BeamlineSummaryPlots_xcs.py
- summaries/BeamlineSummaryPlots_xpp.py
- summaries/PedestalPlot.py
This PR fixes summary plot imports following the new `smalldata_tools` directory structure.
Checklist
-------------
> BUG Fix summary plot imports

- setup_scripts/smd_setup.sh
For the deployment of smd in UED we need to make the arp jobs in the elog
> add ued to sms_setup

- smalldata_tools/lcls2/hutch_default.py
> remove dia from lcl2 list, add default detectors for ued

- .github/workflows/black.yml
- smalldata_tools/ana_funcs/roi_rebin.py
Takes two arguments - axis and idx, defaulting to 0 and None respectively, Will return elements along the specified axis at the specified index. If idx is None, the index of highest pixel will be used.
> Adding lineoutFunc

- smalldata_tools/ana_funcs/azimuthalBinning.py
fix needed for changes in ana 4.0.65
> Bug/ana 4.0.65

- lcls2_producers/prod_config_ued.py
First version of the ued producer config file
> first simple ued prod config

- lcls2_producers/prod_config_ued.py
epix detector should not be in the config file.
> epix quad not default detector

- arp_scripts/make_svd_basis.sh
- lcls2_producers/prod_config_rix.py
- lcls2_producers/smd_producer.py
- smalldata_tools/ana_funcs/smd_svd.py
- smalldata_tools/ana_funcs/svd_waveform/make_waveform_basis_psana1.py
- smalldata_tools/ana_funcs/svd_waveform/make_waveform_basis_psana2.py
- smalldata_tools/ana_funcs/svd_waveform/svd_waveform_processing.py
Add support for svd fit in LCLS2.
This also includes some fixes and improvements.
Example usage for the make_basis script:
`./arp_scripts/make_svd_basis.sh -e rixx1011723 -r 146 -d rix_fim1 --channel -1 -b 50`
> Add svd waveform fit for LCLS2

- lcls1_producers/cube_config_xcs.py
- lcls1_producers/cube_config_xpp.py
- lcls1_producers/letsCube.py
- smalldata_tools/lcls1/SmallDataAna_psana.py
- smalldata_tools/lcls1/cube/cube_rank0_utils.py
When a given cube fails because of no event in it (bad filters or no laser/on/off, the script was just failing.
This takes care of handling this.
Also adds run-dependent filters.
> Handle empty cubes. Skip graciously instead of failing.

- smalldata_tools/common/epicsarchive.py
The daily saving change messed up our archiver retrieval code... This fixes it.
> DEBUG: timezone for timestamp to datetime

- lcls1_producers/cube_config_xcs.py
Change a few XCS cube defaults
> Update XCS cube config for XCS

- lcls2_producers/prod_config_rix.py
This new default will ensure that some thoughts will be put in selecting the proper integrating detector.
> Better default config for integrating detector

- lcls2_producers/prod_config_rix.py
- lcls2_producers/smd_producer.py
- smalldata_tools/__init__.py
- smalldata_tools/ana_funcs/smd_svd.py
- smalldata_tools/common/epicsarchive.py
- smalldata_tools/lcls1/BaseSmallDataAna_psana.py
- smalldata_tools/lcls1/SmallDataAna_psana.py
- smalldata_tools/lcls2/DetObject.py
- smalldata_tools/lcls2/SmallDataAna_psana.py
- smalldata_tools/lcls2/default_detectors.py
Add a run-dependent way of defining the integrating detectors list
Unified and less verbose logger
> better handling of logging and run-based integrating detectors

- lcls1_producers/smd_producer_xcs_ljh.py
XCS liquid jet smd_producer.py file. The purpose is so XCS liquid jet scientists can copy from this custom file that I will maintain to be up-to-date with the standard smd_producer.py file, instead of copying smd_producer.py files from old XCS liquid jet experiments which may be outdated.
> XCS liquid jet smd_producer

- lcls2_producers/prod_config_rix.py
- lcls2_producers/smd_producer.py
Hopefully instantiating the datasource twice with different arguments won't lead to any issues with env var or python caching...
> Test integrating detector presence

- lcls1_producers/smd_producer_xcs_ljh.py
Scientist additions to the xcs liquid jet small data producer template
> small data xcs liquid jet

- lcls2_producers/prod_config_qrix.py
> add qrix config

- lcls2_producers/prod_config_mfx.py
- setup_scripts/make_arp_jobs_lcls2.py
- summaries/BeamlineSummaryPlots_mfx.py
This PR is a minor change to `prod_config_mfx.py` for new detector names. The summary plots are also updated in a first-pass/interim for the LCLS2 MFX.
Checklist
-------------
Testing
-------------
This configuration was run for the entirety of `mfx100852324`. eLog has examples of summaries, the logs showing succesful production are visible as well.
> MNT Additional updates to MFX config. First translation of MFX summary to LCLS2

- lcls2_producers/cube_config_crix.py
- lcls2_producers/cube_config_qrix.py
- lcls2_producers/lets_cube.py
- lcls2_producers/prod_config_crix.py
- lcls2_producers/prod_config_qrix.py
- lcls2_producers/prod_config_rix.py
- lcls2_producers/smd_producer.py
- smalldata_tools/ana_funcs/detector_corrections.py
- smalldata_tools/lcls2/DetObject.py
- smalldata_tools/lcls2/cube/cube.py
Add the requested axis_svls analysis flow with droplet, curve correction and projection.
Other key updates include the introduction of a `NullDetObject` class for better handling of missing detectors, updates to polynomial correction logic, and adjustments to the detector configuration files.
* Added support for `PolynomialCurveCorrection` in `axis_svls` processing, enabling polynomial corrections and projections to be applied in a modular manner (`lcls2_producers/cube_config_crix.py`).
* Added logic in `define_dets` to handle droplet and projection functions as sub-functions of polynomial corrections, ensuring proper chaining of operations (`lcls2_producers/smd_producer.py`).
* Introduced a `NullDetObject` class to handle cases where a detector is not present in the data, avoiding …
> axis_svls worflow

- lcls1_producers/smd_producer.py
- smalldata_tools/utilities.py
> smalldata_tools only runs on S3DF
