- smalldata_tools/DetObject.py
Old code hard-coded some small rayon specific information. Fixed this. I kept the old code as fall back. This could and should likely be cleaned up in the future.
> fix rayonix to properly treat both big&small. 

- examples/ReadElogData.py
- examples/postParamsToElog.py
Add script to read data from the run tables (example to find time tool calibration runs)
Example script from Murali about how to post data to the log run table interface.
> add examples to read&post data from the elog runtables

- smalldata_tools/utilities_FitCenter.py
Use zip instead of itertools.izip iterator to keep fit from defaulting to forceobj=False
Calculate limits before loop
Was about 440 s for single iteration, now about 0.5 s.  Total time including 0.8 s canny edge finding is less than 3 seconds now.
> remove duplicate calcs, use zip for jit compilation recognition

- smalldata_tools/utilities_FitCenter.py
zip also causes forceobj to défault to False.  It doesn't seem to fail everytime, but it always works if we pass the zip object.  Found this during attempt to refactor a bit.
> apparently zip causes jit to fail occasionally as well

- arp_scripts/submit_small_data.sh
- examples/smalldata_producer_arp.py
- smalldata_tools/SmallDataUtils.py
- smalldata_tools/utilities.py
Add the arp version of SmallDataProducer.py (basic)
Add the bash script to kick off ARP run (basic)
Fix typo for Scipy
Comment out detector (for now), that apparently doesn't exist in impDetector now?
Initial working version,  next PR will be to expand bash submit script to include all the options
ARP output:
DEBUG:__main__:Analayzing data for EXP:cxic00318 - RUN:5
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): pswww.slac.stanford.edu:443
DEBUG:urllib3.connectionpool:https://pswww.slac.stanford.edu:443 "GET /ws/lgbk/lgbk/ws/activeexperiment_for_instrument_station?station=0&instrument_name=CXI HTTP/1.1" 200 688
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): pswww.slac.stanford.edu:443
DEBUG:urllib3.connectionpool:https://pswww.slac.stanford.edu:443 "GET …
> add initial small data producer arp and arp script

- smalldata_tools/DetObject.py
add self.ped=None for waveform detectors so that the rewritten ROI function still works.
> set default pedestal for acqiris to that ROI works

- smalldata_tools/ana_funcs/roi_rebin.py
Currently, the thresholds are applied to det.evt.dat which is passed to all functions, meaning functions run after the ROI will see a thresholded image and not the nominal detector data.
> Move thresholding to later in code.

- smalldata_tools/SmallDataUtils.py
- smalldata_tools/ana_funcs/sparsifyFunc.py
Now not specifying nData will give you a 'var array'. nData==0 is a ragged array and nData > 0 the good, old rectangular array.
h5ls  /reg/d/psdm/mec/mecx45520/scratch/snelson/mecx52320_Run0286.h5/epix100a_1_XTCS/var_droplet_sparse
col                      Dataset {119/Inf}
data                     Dataset {119/Inf}
npix                     Dataset {119/Inf}
row                      Dataset {119/Inf}
tile                     Dataset {119/Inf}
h5ls -d  /reg/d/psdm/mec/mecx45520/scratch/snelson/mecx52320_Run0286.h5/epix100a_1_XTCS/var_droplet_sparse_len
var_droplet_sparse_len   Dataset {3/Inf}
Data:
(0) 24, 44, 51
Code to read this will be similar to the changes coming up for the more general droplet2phot implementation.
> finally include the var/flat arrays as sparsifyFunc option

- summaries/PedestalPlot.py
Tested successfully on run 4 of mfxlu7521 
```bash
[fpoitevi@psanagpu108 scratch]$ tail -f slurm-425643.out
Working on plots for  epix10k2M
Made Directory to save data: /reg/d/psdm/mfx/mfxlu7521/stats/summary/Pedestals/Pedestals_Run004
URL: https://pswww.slac.stanford.edu/ws-auth/lgbk//run_control/mfxlu7521/ws/add_run_params
<Response [200]>
```
> PedestalPlot reports number of bad pixels as run params for each detector.

- smalldata_tools/BaseSmallDataAna_psana.py
- smalldata_tools/DetObject.py
- smalldata_tools/SmallDataAna_psana.py
Allow MakeMask to accept an extMask parameter which, if not None, is the properly-shaped mask to create and apply.
This requires knowing the shape of the raw data, so the rawShape property was added to the detector object.  This is initialized by the _getRawShape method which is called after any data retrieval.
> Add external mask parameter to MakeMask

- summaries/PedestalPlot.py
Description
-----------------
- When running `PedestalPlot` after makepeds, the number of bad pixels for each detector will be reported in an HTML posted to the eLog.
- The change in the number of bad pixels will also be reported (from the second DARK run moving on).
Change Log
- Changes to `PedestalPlot.py`
- Add an optional `request_run` parameter to `statusStats` 
- Used to pull detector status info from previous DARK runs
- New function `postBadPixMsg(detectors, exp, run, ...)` which determines DARK run pixel status for `detectors` in experiment `exp`, for DARK runs up to and including a provided `run` number.
- Currently configured to post a message to the eLog with the current DARK run's bad pixel count as well as the change in that count versus the previous DARK …
> Update bad pixel reporting in eLog

- smalldata_tools/DetObject.py
- summaries/PedestalPlot.py
Change Log
- Sort the detector names in descending alphabetical order prior to passing the list to `postBadPixMsg`
- Catch a number of errors which if uncaught cause the `PedestalPlot` jobs to fail. These seem to occur if a detector is added in later runs. The script checks for all detectors present in the current run in all PREVIOUS runs and if one was added later, it may not be present. An example of this can be seen in `mecl1002021` (check the logs under `Workflow > Control` for `PedestalPlot` submissions).
- Catches `TypeError` and presents a debug level message.
- Catches `KeyError` and presents a debug level message.
- If the detector is not present it will append a `0` for the number of bad pixels for that detector in that particular run.
- Convert `self.trbit` …
> Improvements to `PedestalPlot`'s elog posting functionality and minor change to DetObject

- summaries/PedestalPlot.py
Change Log
- Check the length of the recorded `bad_pix` list instead of the length of the `dark_runs` list in `PedestalPlot.postBadPixMsg`.
- This results in displaying a `-` in the eLog post for the difference in bad pixel count for a detector if it is present in the current run but not the previous run. Previously it would display the current number of bad pixels.
> MNT Check len(bad_pix) instead of len(dark_runs) in PedestalPlot.postBadPixMsg

- smalldata_tools/SmallDataUtils.py
Change Log
- Provide MFX beam code for laser on/off.
- Include `lxt` and `txt` in the standard epics detector PV list for MFX.
> ENH/Provide beam code and default PVs for MFX

- producers/update_run_tables.py
- smalldata_tools/epicsarchive.py
This also includes some changes to the epicsarchiver module:
- Don't round to the nearest second if the new useMS parameter is True.
- Get religion about having all datetimes in UTC.  Moreover, convert to UTC using standard routines.
One important point to be discussed is that this script currently just grabs data from the archiver, and puts in the last value prior to the start of the run.  If an archiver API exists to test if the PV was connected at this point, we should add a check here.  If no such API exists, it would not be unreasonable to assume "old" values (for some definition of old) are no longer valid.  (We might want to add these anyway... it's a point of discussion, as I said.)
> First pass script to update run tables

- producers/smd_producer.py
Increase live mode timeout, so that the live mode stops failing in the ARP
> fix for live mode failure

- lcls1_producers/smd_producer.py
- lcls2_producers/smd_producer.py
sys.exit does not properly kill all cores. Raising an exception will.
> make job fail for real if xtc files are not found

- lcls1_producers/smd_producer.py
This PR fixes a minor bug in the producer when extracting droplet parameters.
Checklist
-------------
> BUG Fix LCLS1 Producer droplet parameter parsing

- summaries/BeamlineSummaryPlots_mfx.py
- summaries/PedestalPlot.py
This PR adds the option to associate a run number to an eLog post. This is done for the `SUMMARY_BAD_PIX` posts from the pedestal plots.
Checklist
-------------
Screenshots
Previously, the bad pixel posts looked like this:
**After this PR, they will include the run number**
> ENH Include run number in eLog posts

- summaries/BeamlineSummaryPlots_cxi.py
- summaries/BeamlineSummaryPlots_mfx.py
- summaries/BeamlineSummaryPlots_rix.py
- summaries/BeamlineSummaryPlots_xcs.py
- summaries/BeamlineSummaryPlots_xpp.py
- summaries/PedestalPlot.py
- summaries/summary_utils.py
This PR adds previous/next buttons to the top of the `BeamlineSummaryPlots` as a small QOL improvement for cycling between runs.
Checklist
-------------
Screenshots
Buttons for navigating forward/back and to the most recent/first run summary that currently exists.
> ENH First draft of prev/next buttons on run summaries

- lcls1_producers/smd_producer.py
This PR uses the `small_data.max` method to produce a true max projection when reducing across MPI ranks for the detector image sum. This is applied to sum algorithms `calib_max` and variants.
Checklist
-------------
Testing
-------------
> ENH Use maximum for MPI reduction when requesting max projection for detector image sum

- smalldata_tools/lcls1/SmallDataAna_psana.py
The det.ped, det.rms, and det.gain parameters do not exist for the Zyla and Alvium cameras, so the code will continue running for those cameras without requiring those parameters.
> Continue through missing detector parameters 

- lcls2_producers/prod_config_mfx.py
- lcls2_producers/smd_producer.py
- setup_scripts/smd_setup.sh
- smalldata_tools/lcls2/DetObject.py
- smalldata_tools/lcls2/default_detectors.py
- smalldata_tools/lcls2/hutch_default.py
This PR provides MFX configuration for smalldata_tools with LCLS2 data. It makes some modifications to `ttDetector` and provides a lightStatus more attuned to hutches still running on LCLS1 timing.
Support for the Jungfrau, FEE (XRT) spectrometer variable length data and ePix100 is also added. Note that `cmpars` and common mode seem to have an indexing bug at the psana level for the ePix100, so for now the options that were previously used in LCLS1 have been commented out.
Checklist
-------------
Testing
-------------
Modify `detectors` in `prod_config_mfx.py` for testing.
- `ePix100` -> **Common mode does not seem to work at psana-level, so not currently passing** `cmpars`
```bash
> ./arp_scripts/submit_smd2.sh -d /sdf/scratch/users/d/dorlhiac -n 120 -e mfxdaq23 -r 5 --interactive
> h5ls …
```
> ENH Support MFX with LCLS2 DAQ

- lcls2_producers/prod_config_mfx.py
- lcls2_producers/smd_producer.py
- smalldata_tools/lcls2/DetObject.py
- smalldata_tools/lcls2/default_detectors.py
- smalldata_tools/lcls2/hutch_default.py
This PR provides addtional detectors for MFX running with the LCLS2 DAQ. It adds the `usbEncoder` for the fast delay stages and a `damageDetector` which behaves like the LCLS1 version (will not work for RIX). Updates the producer file and config file to include droplet.
Checklist
-------------
Testing
-------------
Run 211 of `mfx101332224`:
```bash
> /sdf/data/lcls/ds/mfx/mfx101332224/results/smalldata_tools/arp_scripts/submit_smd2.sh --partition milano --postRuntable --nodes 2 --wait --interactive --nevents 5 --experiment mfx101332224 --run 211 --directory /sdf/scratch/users/d/dorlhiac
[ 2025-05-09 10:06:29,070 | INFO | smd_producer.py] ebeamh: ebeamh
[ 2025-05-09 10:06:29,070 | INFO | smd_producer.py] pcav: pcav
[ 2025-05-09 10:06:29,070 | INFO | smd_producer.py] gasdet: gasdet
[ …
```
> ENH New damage and USB Encoder dets and updated MFX config.

- lcls2_producers/prod_config_qrix.py
- lcls2_producers/smd_producer.py
- smalldata_tools/lcls1/hutch_default.py
Add DCCM motors to the XCS hutch default pv list.
> Add Xcs hutch defaults dccm

- lcls1_producers/cube_config_xcs.py
Fails looking for the "save_tiff" argument without this line, other hutches have it.
> adding save_tiff arg to xcs cube, or else fails

- lcls2_producers/prod_config_mfx.py
- lcls2_producers/smd_producer.py
- smalldata_tools/lcls2/DetObject.py
This PR adds configuration options for sum algorithms in the LCLS2 producer.
Note this exists similarly in LCLS1 (minus the `"all"` key), but the retrieval function is named differently. The camel-case LCLS1 version is different than the naming style used for the LCLS2 producer, but for consistency we can use it here if that is preferred.
Checklist
-------------
- Includes an `"all"` key which allows application of the algoirthm to all detectors
- Sets a default sum algorithm if none are defined.
Testing
-------------
Tested against `mfx100864724` using the standard `prod_config_mfx.py`, except with the only change being the addition of the `jungfrau` to the detectors list:
```bash
>  ./arp_scripts/submit_smd2.sh -e mfx100864724 -r 206 --directory /sdf/scratch/users/d/dorlhiac --nevents 5 …
```
> ENH LCLS2 Sum Algorithm Config

- lcls1_producers/smd_producer.py
This PR fixes a minor bug when no ROIs are defined in LCLS1.
The `roi_args` variable which gets used for the ROIs is unbound if not in the config file. The empty dict had a different name `rois_args`. This makes the names identical.
Checklist
-------------
Testing
-------------
> BUG Unbound error if no ROI defined.

- setup_scripts/make_arp_jobs_lcls2.py
This PR fixes a minor bug in the ARP job setup script. The conditional checking `--all_events` previously always evaluated to `True`. This leads to jobs being created with with the `--all_events` flag, and their trigger being `MANUAL`, regardless of if you passed `--all_events` to the setup script.
Checklist
-------------
Testing
-------------
> BUG Fix conditional in job definition script
